### PR TITLE
Add logic for cutting over from ucarp

### PR DESCRIPTION
**Pull request by TravisWhitehead**
This PR includes:
* Logic for removing `ucarp` on production when we cut over to `keepalived`
* Instructions for testing cutover using `chef-provisioning`

-----

From the testing I did, just adding the recipes for `osl-keepalived` and removing `ucarp` from the run lists will be just fine. Removing the `ucarp` package doesn't unbind the VIP, and `keepalived` works as expected after switching over.

-----

**Testing ucarp -> keepalived cutover with chef-provisioning**
1. Add `cookbook 'ucarp', git: 'git@github.com:osuosl-cookbooks/ucarp', branch: 'whitehet/ucarp-remove'` to `Berksfile`
2. Update `test/cookbooks/keepalived_test/recipes/provisioning.rb` and comment out keepalived-related logic (but keep firewall & httpd stuff). Add:
```ruby
node.default['ucarp']['data_bag']['cluster'] = 'keepalived-test'
include_recipe 'ucarp::data_bag'
```
3. `rake clean && rake keepalived`
4. Undo the changes from step 2, and do `include_recipe 'ucarp::remove'` before the keepalived logic.
5. `rake keepalived`
6. Test that keepalived is working (see #2).

### CODE REVIEW

**Comment by TravisWhitehead** [comment]
[keepalived](https://trello.com/c/68d7MKNW/236-keepalived)

**Comment by ramereth** [comment]
@TravisWhitehead I think it might make more sense to put most of this logic in a ``remove`` recipe in the ucarp cookbook that should basically reverse everything the ``data_bag`` recipe does. That way we don't include ucarp in the cookbook metadata and we can just call ``ucarp::remove`` in the run list. Thoughts?

I realize this is a bit more of a pain for a one-time deal, but I think it might be cleaner.

**Comment by TravisWhitehead** [comment]
Yeah, I agree that would make more sense. I'll move it over to the ucarp cookbook.

**Comment by TravisWhitehead** [comment]
@ramereth Would you still like me to keep the logic/instructions in the provisioning recipe for testing the ucarp cutover? Or remove it? I don't really foresee us using it ever in the future.

**Comment by ramereth** [comment]
@TravisWhitehead If you can at least document it here in this PR that's good enough for me. I agree that it shouldn't be included forever.

**Comment by TravisWhitehead** [comment]
@ramereth I've removed ucarp-related logic from this cookbook, and created a PR for ucarp: https://github.com/osuosl-cookbooks/ucarp/pull/11

**Comment by ramereth** [comment]
@TravisWhitehead is this PR in limbo until that PR is merged then?

**Comment by TravisWhitehead** [comment]
@ramereth I think this PR can be closed (unless we want to leave in convenience-stuff for testing ucarp cutover...), though folks can follow these instructions to test cutover if desired.

**Comment by ramereth** [comment]
@TravisWhitehead I vote to close it

**Pull request closed without merging**
