### PR TITLE
Add mysql-vip1 configuration

### PR DESCRIPTION
**Pull request by EMH333**

### CODE REVIEW

**Comment by ramereth** [comment]
@EMH333 please rebase and I can look at this

**Review by ramereth — APPROVED** [review]
minor bump

**Comment by EMH333** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.4.0.  Have a nice day!

**Pull request merged**
