### PR TITLE
Bump keepalived to Chef 17-compliant version

### PR DESCRIPTION
**Pull request by detjensrobert**
Also re-enables multi-node tests with a pinned Openstack provider.

### CODE REVIEW

**Comment by ramereth** [comment]
@detjensrobert I tried running the multi-node suite (at least for centos-7) and it failed to pass tests. Can you please look into that since you're enabling that again?

**Comment by detjensrobert** [comment]
A second verify passes fine, looks like keepalived might need a second or two to settle. C8 passes just fine.

**Review by ramereth — APPROVED** [review]
Minor bump

**Comment by detjensrobert** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.2.0.  Have a nice day!

**Pull request merged**
